export const FETCH_TOPLINE = "FETCH_TOPLINE";
export const FETCH_TOPLINE_FAILED = "FETCH_TOPLINE_FAILED";
export const FETCH_TOPLINE_SUCCESS = "FETCH_TOPLINE_SUCCESS";

export const FETCH_POLITICS = "FETCH_POLITICS";
export const FETCH_POLITICS_FAILED = "FETCH_POLITICS_FAILED";
export const FETCH_POLITICS_SUCCESS = "FETCH_POLITICS_SUCCESS";

export const FETCH_SPORTS = "FETCH_SPORTS";
export const FETCH_SPORTS_FAILED = "FETCH_SPORTS_FAILED";
export const FETCH_SPORTS_SUCCESS = "FETCH_SPORTS_SUCCESS";

export const FETCH_ENTMT = "FETCH_ENTMT";
export const FETCH_ENTMT_FAILED = "FETCH_ENTMT_FAILED";
export const FETCH_ENTMT_SUCCESS = "FETCH_ENTMT_SUCCESS";

export const FETCH_SEARCH = "FETCH_SEARCH";
export const FETCH_SEARCH_FAILED = "FETCH_SEARCH_FAILED";
export const FETCH_SEARCH_SUCCESS = "FETCH_SEARCH_SUCCESS";

export const FETCH_LATEST = "FETCH_LATEST";
export const FETCH_LATEST_FAILED = "FETCH_LATEST_FAILED";
export const FETCH_LATEST_SUCCESS = "FETCH_LATEST_SUCCESS";

export const CHANGE_LANG = "CHANGE_LANG";
export const SHOW_RESULT_MODAL = "SHOW_RESULT_MODAL";
export const CLOSE_RESULT_MODAL = "CLOSE_RESULT_MODAL";
